:github-root: https://github.com
:github: {github-root}/Edwolt
:gitlab: https://gitlab.com/Edwolt
:gist: https://gist.github.com/Edwolt

:badge-root: https://img.shields.io/tokei/lines
:badge: {badge-root}/github/Edwolt
:badge-gitlab: {badge-root}/gitlab/Edwolt
:badge-gist: {badge-root}/gist.github/Edwolt
:badge-style: style=flat-square

== Antigos
* {github}/Jogo-de-Tabuleiro[Jogo de Tabuleiro]
  image:{badge}/Jogo-de-Tabuleiro?{badge-style}[Lines of Code]
* {github}/Jogo-de-Tabuleiro-2[Jogo de Tabuleiro 2]
  image:{badge}/Jogo-de-Tabuleiro-2?{badge-style}[Lines of Code]
* {github}/RPG[RPG]
  image:{badge}/RPG?{badge-style}[Lines of Code]
// Truco

== Gists
* {gist}/7b74c332715207c876628dd9a5e6e997[Obscure Hello World!]
  image:{badge-gist}/7b74c332715207c876628dd9a5e6e997?{badge-style}[Lines of Code]
* {gist}/95d32eb40e79f4f73a6a4a102753292a[X1B]: Terminal Color
  image:{badge-gist}/95d32eb40e79f4f73a6a4a102753292a?{badge-style}[Lines of Code]

== Para Game Jaaj
* {github}/BoucingBall[Boucing Ball]
  image:{badge}/BoucingBall?{badge-style}[Lines of Code]
* {github}/JogoDaArminha[Jogo da Arminha]
  image:{badge}/JogoDaArminha?{badge-style}[Lines of Code]

== Estudos
* {gitlab}/Estudos[Estudos]
  image:{badge-gitlab}/Estudos?{badge-style}[Lines of Code]
* {github}/TinyRenderer[Tiny Renderer]
  image:{badge}/TinyRenderer?{badge-style}[Lines of Code]

== Ciências da Computação
* Eletrônica para computação
** {github}/Termometro-Arduino[Termometro Arduino]
   image:{badge}/Termometro-Arduino?{badge-style}[Lines of Code]

* Introdução a Ciências da Computação
** {github}/TrabalhoICC-SegmentacaoDeImagem[Segmentação de Imagem]
   image:{badge}/TrabalhoICC-SegmentacaoDeImagem?{badge-style}[Lines of Code]

* Organização de Computadores
** {github}/MIPS-Calculadora[MIPS Calculadora]
   image:{badge}/MIPS-Calculadora?{badge-style}[Lines of Code]
** {github}/PICMC-Simul[Simulador do Processador ICMC implementado no próprio Simulador ICMC]
   image:{badge}/PICMC-Simul?{badge-style}[Lines of Code]
** {github}/Processador-MASM[Processador MASM (My Assembly)]
   image:{badge}/Processador-MASM?{badge-style}[Lines of Code]

* Organização de Arquivos
** {github}/OrganizacaoDeArquivos-Trabalho[Trabalho de Organização de Arquivos]
   image:{badge}/OrganizacaoDeArquivos-Trabalho?{badge-style}[Lines of Code]

* Desenvolvimento Web
** {github}/Petshop-Mockup[Petshop - Mockup]
   image:{badge}/Petshop-Mockup{badge-style}[Lines of Code]
** {github-root}/FulecoRafa/petshop-front[Petshop - Frontend]
   image:{badge-root}/github/FulecoRafa/petshop-front[Lines of Code]
** {github-root}/FulecoRafa/petshop-back[Petshop - Back]
   image:{badge-root}/github/FulecoRafa/petshop-back[Lines of Code]

* Programação Orientada à Objetos
** {github-root}/lucasyamamoto/SSC0103-Programacao-Orientada-a-Objetos-Projeto-Final[Projeto Final]
   image:{badge-root}/github/lucasyamamoto/SSC0103-Programacao-Orientada-a-Objetos-Projeto-Final[Lines of Code]

* Algoritmos Evolutivos
** {github}/Jogo-da-Velha[Jogo da Velha]
   image:{badge}/Jogo-da-Velha{badge-style}[Lines of Code]

* Base de Dados
** {github-root}/WictorDalbosco/TrabalhoBD[Plataforma de Agregação de Cursos]
   image:{badge-root}/github/WictorDalbosco/TrabalhoBD{badge-style}[Lines of Code]

* Visualização Computacional
** {github-root}/NathanTBP/nobeldatavisualization[Nobel Visualization]
   image:{badge-root}/github/NathanTBP/nobeldatavisualization{badge-style}[Lines of Code]
