:github-root: https://github.com
:github: {github-root}/Edwolt
:gitlab: https://gitlab.com/Edwolt
:gist: https://gist.github.com/Edwolt

:badge-root: https://img.shields.io/tokei/lines
:badge: {badge-root}/github/Edwolt
:badge-gitlab: {badge-root}/gitlab/Edwolt
:badge-gist: {badge-root}/gist.github/Edwolt
:badge-style: style=flat-square

:desc: [ - ]

== Antigos
* {github}/Jogo-de-Tabuleiro[Jogo de Tabuleiro]
  image:{badge}/Jogo-de-Tabuleiro?{badge-style}{desc}
* {github}/Jogo-de-Tabuleiro-2[Jogo de Tabuleiro 2]
  image:{badge}/Jogo-de-Tabuleiro-2?{badge-style}{desc}
* {github}/RPG[RPG]
  image:{badge}/RPG?{badge-style}{desc}
// Truco

== Gists
* {gist}/7b74c332715207c876628dd9a5e6e997[Obscure Hello World!]
//image:{badge-gist}/7b74c332715207c876628dd9a5e6e997?{badge-style}[ - ]
* {gist}/95d32eb40e79f4f73a6a4a102753292a[X1B]: Terminal Color
//image:{badge-gist}/95d32eb40e79f4f73a6a4a102753292a?{badge-style}[ - ]

== Para Game Jaaj
* {github}/BoucingBall[Boucing Ball]
  image:{badge}/BoucingBall?{badge-style}[ - ]
* {github}/JogoDaArminha[Jogo da Arminha]
  image:{badge}/JogoDaArminha?{badge-style}[ - ]

== Estudos
* {gitlab}/Estudos[Estudos]
  image:{badge-gitlab}/Estudos?{badge-style}[ - ]
* {github}/TinyRenderer[Tiny Renderer]
  image:{badge}/TinyRenderer?{badge-style}[ - ]

== Projetos
* {github}/FieldViz[Vector Field Visualization]
  image:{badge}/FieldViz?{badge-style}[ - ]

== Ciências da Computação
* Eletrônica para computação
** {github}/Termometro-Arduino[Termometro Arduino]
   image:{badge}/Termometro-Arduino?{badge-style}[ - ]

* Introdução a Ciências da Computação
** {github}/TrabalhoICC-SegmentacaoDeImagem[Segmentação de Imagem]
   image:{badge}/TrabalhoICC-SegmentacaoDeImagem?{badge-style}[ - ]

* Organização de Computadores
** {github}/MIPS-Calculadora[MIPS Calculadora]
   image:{badge}/MIPS-Calculadora?{badge-style}[ - ]
** {github}/PICMC-Simul[Simulador do Processador ICMC implementado no próprio Simulador ICMC]
   image:{badge}/PICMC-Simul?{badge-style}[ - ]
** {github}/Processador-MASM[Processador MASM (My Assembly)]
   image:{badge}/Processador-MASM?{badge-style}[ - ]

* Organização de Arquivos
** {github}/OrganizacaoDeArquivos-Trabalho[Trabalho de Organização de Arquivos]
   image:{badge}/OrganizacaoDeArquivos-Trabalho?{badge-style}[ ]

* Desenvolvimento Web
** {github}/Petshop-Mockup[Petshop - Mockup]
   image:{badge}/Petshop-Mockup?{badge-style}[ ]
** {github-root}/FulecoRafa/petshop-front[Petshop - Frontend]
   image:{badge-root}/github/FulecoRafa/petshop-front?{badge-style}[ ]
** {github-root}/FulecoRafa/petshop-back[Petshop - Back]
   image:{badge-root}/github/FulecoRafa/petshop-back?{badge-style}[ ]

* Programação Orientada à Objetos
** {github-root}/lucasyamamoto/SSC0103-Programacao-Orientada-a-Objetos-Projeto-Final[Projeto Final]
   image:{badge-root}/github/lucasyamamoto/SSC0103-Programacao-Orientada-a-Objetos-Projeto-Final?{badge-style}[ ]

* Algoritmos Evolutivos
** {github}/Jogo-da-Velha[Jogo da Velha]
   image:{badge}/Jogo-da-Velha?{badge-style}[ ]

* Base de Dados
** {github-root}/WictorDalbosco/TrabalhoBD[Plataforma de Agregação de Cursos]
   image:{badge-root}/github/WictorDalbosco/TrabalhoBD?{badge-style}[ ]

* Visualização Computacional
** {github-root}/NathanTBP/nobeldatavisualization[Nobel Visualization]
   image:{badge-root}/github/NathanTBP/nobeldatavisualization?{badge-style}[ ]
