// :show-badges:

:github-root: https://github.com
:github: {github-root}/Edwolt
:gitlab: https://gitlab.com/Edwolt
:gist: https://gist.github.com/Edwolt

:loc-root: https://img.shields.io/tokei/lines
:loc: {loc-root}/github/Edwolt
:loc-gitlab: {loc-root}/gitlab/Edwolt
:loc-gist: {loc-root}/gist.github.com/Edwolt

:commit-gh: https://img.shields.io/github/last-commit
:commit: https://img.shields.io/github/last-commit/Edwolt
:commit-gitlab: https://img.shields.io/gitlab/last-commit/Edwolt
:commit-gist: https://img.shields.io/github/gist/last-commit

:badge-style: style=flat-square

:desc: [ - ]

== Projetos

* {github}/FieldViz[Vector Field Visualization]
ifdef::show-badges[]
  image:{loc}/FieldViz?{badge-style}{desc}
  image:{commit}/FieldViz?{badge-style}{desc}
endif::show-badges[]

== Jogos
* {github}/RPG[RPG]
ifdef::show-badges[]
  image:{loc}/RPG?{badge-style}{desc}
  image:{commit}/RPG?{badge-style}{desc}
endif::show-badges[]

* Jogos de Xadrez:
** {github}/Jogo-de-Tabuleiro[Jogo de Tabuleiro]
ifdef::show-badges[]
  image:{loc}/Jogo-de-Tabuleiro?{badge-style}{desc}
  image:{commit}/Jogo-de-Tabuleiro?{badge-style}{desc}
endif::show-badges[]

** {github}/Jogo-de-Tabuleiro-2[Jogo de Tabuleiro 2]
ifdef::show-badges[]
  image:{loc}/Jogo-de-Tabuleiro-2?{badge-style}{desc}
  image:{commit}/Jogo-de-Tabuleiro-2?{badge-style}{desc}
endif::show-badges[]

// Truco

=== Fellowship of The Game (FoG)
* {github}/SpaceInvaders[SpaceInvaders] (Processo Seletivo do Fog)
ifdef::show-badges[]
    image:{loc}/SpaceInvaders?{badge-style}{desc}
    image:{commit}/SpaceInvaders?{badge-style}{desc}
endif::show-badges[]

=== Para Game Jaaj
* {github}/BoucingBall[Boucing Ball]
ifdef::show-badges[]
  image:{loc}/BoucingBall?{badge-style}{desc}
  image:{commit}/BoucingBall?{badge-style}{desc}
endif::show-badges[]

* {github}/JogoDaArminha[Jogo da Arminha]
ifdef::show-badges[]
  image:{loc}/JogoDaArminha?{badge-style}{desc}
  image:{commit}/JogoDaArminha?{badge-style}{desc}
endif::show-badges[]

== Gists
* {gist}/7b74c332715207c876628dd9a5e6e997[Obscure Hello World!]
ifdef::show-badges[]
  image:{loc-gist}/7b74c332715207c876628dd9a5e6e997?{badge-style}{desc}
  image:{commit-gist}/7b74c332715207c876628dd9a5e6e997?{badge-style}{desc}
endif::show-badges[]

* {gist}/95d32eb40e79f4f73a6a4a102753292a[X1B]: Terminal Color
ifdef::show-badges[]
  image:{loc-gist}/95d32eb40e79f4f73a6a4a102753292a?{badge-style}{desc}
  image:{commit-gist}/95d32eb40e79f4f73a6a4a102753292a?{badge-style}{desc}
endif::show-badges[]


== Estudos
* {gitlab}/Estudos[Estudos]
ifdef::show-badges[]
  image:{loc-gitlab}/Estudos?{badge-style}{desc}
  image:{commit-gitlab}/Estudos?{badge-style}{desc}
endif::show-badges[]

* {github}/TinyRenderer[Tiny Renderer]
ifdef::show-badges[]
  image:{loc}/TinyRenderer?{badge-style}{desc}
  image:{commit}/TinyRenderer?{badge-style}{desc}
endif::show-badges[]

== Ciências da Computação
=== Eletrônica para computação
* {github}/Termometro-Arduino[Termometro Arduino]
ifdef::show-badges[]
   image:{loc}/Termometro-Arduino?{badge-style}{desc}
   image:{commit}/Termometro-Arduino?{badge-style}{desc}
endif::show-badges[]

=== Introdução a Ciências da Computação
* {github}/TrabalhoICC-SegmentacaoDeImagem[Segmentação de Imagem]
ifdef::show-badges[]
   image:{loc}/TrabalhoICC-SegmentacaoDeImagem?{badge-style}{desc}
   image:{commit}/TrabalhoICC-SegmentacaoDeImagem?{badge-style}{desc}
endif::show-badges[]

=== Organização de Computadores
* {github}/MIPS-Calculadora[MIPS Calculadora]
ifdef::show-badges[]
   image:{loc}/MIPS-Calculadora?{badge-style}{desc}
   image:{commit}/MIPS-Calculadora?{badge-style}{desc}
endif::show-badges[]

* {github}/PICMC-Simul[Simulador do Processador ICMC implementado no próprio Simulador ICMC]
ifdef::show-badges[]
   image:{loc}/PICMC-Simul?{badge-style}{desc}
   image:{commit}/PICMC-Simul?{badge-style}{desc}
endif::show-badges[]

* {github}/Processador-MASM[Processador MASM (My Assembly)]
ifdef::show-badges[]
   image:{loc}/Processador-MASM?{badge-style}{desc}
   image:{commit}/Processador-MASM?{badge-style}{desc}
endif::show-badges[]

=== Organização de Arquivos
* {github}/OrganizacaoDeArquivos-Trabalho[Trabalho de Organização de Arquivos]
ifdef::show-badges[]
   image:{loc}/OrganizacaoDeArquivos-Trabalho?{badge-style}{desc}
   image:{commit}/OrganizacaoDeArquivos-Trabalho?{badge-style}{desc}
endif::show-badges[]

=== Desenvolvimento Web
* {github}/Petshop-Mockup[Petshop - Mockup]
ifdef::show-badges[]
   image:{loc}/Petshop-Mockup?{badge-style}{desc}
   image:{commit}/Petshop-Mockup?{badge-style}{desc}
endif::show-badges[]

* {github-root}/FulecoRafa/petshop-front[Petshop - Frontend]
ifdef::show-badges[]
   image:{loc-root}/github/FulecoRafa/petshop-front?{badge-style}{desc}
   image:{commit-gh}/FulecoRafa/petshop-front?{badge-style}{desc}
endif::show-badges[]

* {github-root}/FulecoRafa/petshop-back[Petshop - Back]
ifdef::show-badges[]
   image:{loc-root}/github/FulecoRafa/petshop-back?{badge-style}{desc}
   image:{commit-gh}/FulecoRafa/petshop-back?{badge-style}{desc}
endif::show-badges[]

=== Programação Orientada à Objetos
* {github-root}/lucasyamamoto/SSC0103-Programacao-Orientada-a-Objetos-Projeto-Final[Projeto Final]
ifdef::show-badges[]
   image:{loc-root}/github/lucasyamamoto/SSC0103-Programacao-Orientada-a-Objetos-Projeto-Final?{badge-style}{desc}
   image:{commit-gh}/lucasyamamoto/SSC0103-Programacao-Orientada-a-Objetos-Projeto-Final?{badge-style}{desc}
endif::show-badges[]

=== Algoritmos Evolutivos
* {github}/Jogo-da-Velha[Jogo da Velha]
ifdef::show-badges[]
   image:{loc}/Jogo-da-Velha?{badge-style}{desc}
   image:{commit}/Jogo-da-Velha?{badge-style}{desc}
endif::show-badges[]
** Obs: Tem uma versão em Rust no repositório

=== Base de Dados
* {github-root}/WictorDalbosco/TrabalhoBD[Plataforma de Agregação de Cursos]
ifdef::show-badges[]
   image:{loc-root}/github/WictorDalbosco/TrabalhoBD?{badge-style}{desc}
   image:{commit-gh}/WictorDalbosco/TrabalhoBD?{badge-style}{desc}
endif::show-badges[]

=== Visualização Computacional
* {github-root}/NathanTBP/nobeldatavisualization[Nobel Visualization]
ifdef::show-badges[]
   image:{loc-root}/github/NathanTBP/nobeldatavisualization?{badge-style}{desc}
   image:{commit-gh}/NathanTBP/nobeldatavisualization?{badge-style}{desc}
endif::show-badges[]

=== Sistemas Operacionais
* {github}/Sistema-de-Reserva-Aviao[Sistemas de Reserva de Avião]: Uso de Threads
ifdef::show-badges[]
   image:{loc}/Sistema-de-Reserva-Aviao?{badge-style}{desc}
   image:{commit}/Sistema-de-Reserva-Aviao?{badge-style}{desc}
endif::show-badges[]


== Privados
* {github}/DotFiles[DotFiles]
ifdef::show-badges[]
endif::show-badges[]

// * Yahtzee
